### ISSUE TITLE
rugpt3xl config not found

### ISSUE THREAD

**Issue by Denis-master** [ai-forever/ru-gpts#89]
hello, I downloaded the rugpt3xl model and it gives me an error that the config.json file was not found.

2022-04-16 15:23:16.589970: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.57M/1.57M [00:09<00:00, 160kB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.23M/1.23M [00:04<00:00, 256kB/s]
404 Client Error: Not Found for url: https://huggingface.co/sberbank-ai/rugpt3xl/resolve/main/config.json
Traceback (most recent call last):
  File "/home/denis/.local/lib/python3.6/site-packages/transformers/configuration_utils.py", line 406, in get_config_dict
    use_auth_token=use_auth_token,
  File "/home/denis/.local/lib/python3.6/site-packages/transformers/file_utils.py", line 1085, in cached_path
    local_files_only=local_files_only,
  File "/home/denis/.local/lib/python3.6/site-packages/transformers/file_utils.py", line 1215, in get_from_cache
    r.raise_for_status()
  File "/home/denis/.local/lib/python3.6/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/sberbank-ai/rugpt3xl/resolve/main/config.json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "rugpt_chitchat.py", line 91, in <module>
    chitchat.load('rugpt_chitchat')
  File "rugpt_chitchat.py", line 25, in load
    self.model = GPT2LMHeadModel.from_pretrained("sberbank-ai/rugpt3xl")
  File "/home/denis/.local/lib/python3.6/site-packages/transformers/modeling_utils.py", line 959, in from_pretrained
    **kwargs,
  File "/home/denis/.local/lib/python3.6/site-packages/transformers/configuration_utils.py", line 360, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/denis/.local/lib/python3.6/site-packages/transformers/configuration_utils.py", line 418, in get_config_dict
    raise EnvironmentError(msg)
OSError: Can't load config for 'sberbank-ai/rugpt3xl'. Make sure that:

- 'sberbank-ai/rugpt3xl' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'sberbank-ai/rugpt3xl' is the correct path to a directory containing a config.json file

**Comment by king-menin** [comment]
If you would like use rugpt3xl please follow this code examples/ruGPT3XL_generation.ipynb
For rugpt3xl  we do not support standart interface from huggingface
